### ISSUE TITLE
error for creating new project

### ISSUE THREAD

**Issue by okapur1** [lokeshwarbandhu/data-upload-scripts#3]
When uploading a data, if I am creating new sample that requires a new project ID, there is a fault
![image](https://github.com/lokeshwarbandhu/Data-tools/assets/126271114/047f7e3b-6a98-4d38-b0f2-7ac8c53cc3e0)

**Comment by lokeshwarbandhu** [comment]
This may occur if there was a space in front of the project name. I have tried at my end and there is no error without spaces. Can you confirm that please?

**Comment by lokeshwarbandhu** [comment]
I have updated the v3 script to check for spaces in project name. @okapur1  Let me know if you are still having any issues.
